// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naedfhnzuwywnltjsqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZWRmaG56dXd5d25sdGpzcWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Mzg2NTMsImV4cCI6MjA3MjIxNDY1M30.htNLAlzpVtriz0MmTaNnv_9N5HOcR4PXSFbaEULc6KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});